
version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "issue-certificate:1:1,email-handler:1:1"
    
  redis:
    container_name: redis_queue
    image: 'redis:alpine'
    restart: always
    ports: 
      - "6379:6379"

  # ms-mail-kafka:
  #   container_name: ms-mail-kafka
  #   build: .
  #   depends_on: 
  #     - kafka
  #   command: npm run start:kafka

  # ms-mail-queue:
  #   container_name: ms-mail-queue
  #   build: .
  #   depends_on: 
  #     - redis
  #   command: npm run start:queue

  # ms-mail-express:
  #   container_name: ms-mail-express
  #   build: .
  #   depends_on: 
  #     - ms-mail-queue
  #     - ms-mail-kafka
  #   ports: 
  #     - "3030:3030"
  #   command: npm run start:express